---
name: Release
on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Ansible Galaxy CLI
        run: pip install ansible

      - name: Publish to Galaxy
        run: |
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
