---
name: Release
on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      # Ansible ist bereits im Ubuntu Image enthalten, wir brauchen keine spezielle Version für den Import trigger: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
      - name: Publish to Galaxy
        run: |
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
